services:
  bind:
    PB\Config\ConfigInterface: PB\Config\YmlConfig
    PB\Library\Responses\ResponseInterface: PB\Library\Responses\ResponseJson
    PB\Library\Requests\RequestInterface:
      main: PB\Library\Requests\Curl
      param: PB\Library\Responses\ResponseJson
